version: '2'
services:
  serveapp:
    build: ../src/serveapp
    image: ansjin/four_microservice:serveapp
    ports:
      - "8080:8080"
    depends_on:
      - 'primeapp'
      - 'movieapp'
      - 'webacapp'
    links:
      - 'primeapp'
      - 'movieapp'
      - 'webacapp'
  primeapp:
    build: ../src/primeapp
    image: ansjin/four_microservice:primeapp
    ports:
      - "9001:9001"
  movieapp:
    build: ../src/movieapp
    ports:
      - "9002:9002"
    restart: always
    image: ansjin/four_microservice:movieapp
    links:
      - mongo
  mongo:
    image: ansjin/movieapp:mongo
    ports:
      - "27017:27017"
  webacapp:
    build: ../src/webacapp
    ports:
      - "9003:9003"
    restart: always
    image: ansjin/four_microservice:webacapp
